### PR TITLE
Allow no-validate parameter for docker registry

### PR DESCRIPTION
**Pull request by ranesagar**
Solves https://github.com/OpsMx/spinnaker-helm/issues/22

From: https://github.com/spinnaker/halyard/blob/master/docs/commands.md#hal-config-provider-docker-registry

`--no-validate: (Default: false) Skip validation.`

### CODE REVIEW

**Comment by ranesagar** [comment]
@abhinaybyrisetty - Can you please review?

**Comment by abhinaybyrisetty** [comment]
Yeah, this change looks good. But, skipping validation shouldn't be recommended unless extremely necessary. Perhaps, making client-timeout as configurable is a better option than skipping validation.

**Review by abhinaybyrisetty — APPROVED** [review]

**Review by abhinaybyrisetty — CHANGES_REQUESTED** [review]
I'm afraid these changes won't fully solve the problem as validation will be done during `hal deploy apply` as well

**Comment by Badbond** [comment]
Thanks for picking this up so fast :pray: 

> Perhaps, making client-timeout as configurable is a better option than skipping validation.

AFAIK, there is no such option. A [ticket](https://togithub.com/spinnaker/spinnaker/issues/5903) was created for this but went stale.

> I'm afraid these changes won't fully solve the problem as validation will be done during `hal deploy apply` as well

@abhinaybyrisetty Fortunately this command does have [parameters](https://spinnaker.io/docs/reference/halyard/commands/#hal-deploy-apply) to configure timeout behavior such as `--wait-for-completion` and `--wait-for-completion-timeout-minutes`. I believe it also has a longer default timeout (but couldn't find official resources on this). Luckily the chart already [allows to pass additional parameters](https://github.com/OpsMx/spinnaker-helm/blob/21c1b4fa02c5f378fdce529afa1772d6e5b95997/charts/spinnaker/templates/configmap/halyard-config.yaml#L28-L31) to this command to do so.

**Comment by abhinaybyrisetty** [comment]
Hi @Badbond 

There is an option to pass along with hal config [command ](https://spinnaker.io/docs/reference/halyard/commands/#hal-config-provider-docker-registry-account-add) **--client-timeout-millis** which will allow us to override timeout. Did you try it?

**Comment by Badbond** [comment]
Thanks for pointing it out @abhinaybyrisetty, I did not see it before. I did just try it but unfortunately it looks like it is not used during validation (executed in Halyard pod):

```
$ time hal config provider docker-registry account edit dockerhub --address index.docker.io \ 
    <account settings & --repositories> \
   --client-timeout-millis 600000
+ Get current deployment
  Success
+ Get dockerhub account
  Success
<-^*_ Edit the dockerhub account>
  Timed out
Validation in Global:
! ERROR Unexpected exception:
  DaemonTaskInterrupted(interruptedTime=1652944810613, message=Task interrupted
  without cause at Thu May 19 07:20:10 GMT 2022)

- Failed to edit account dockerhub for provider dockerRegistry.
  Task killed because it was taking too long.

real	1m8.203s
user	0m5.512s
sys	0m0.523s
```

**Comment by abhinaybyrisetty** [comment]
@Badbond then I think, having the option to skip validation is the more convenient at the moment. Let's submit that.

**Comment by abhinaybyrisetty** [comment]
@ranesagar I made some changes to the folder structure and added a github action to automate release. You might want to rebase the code.

**Comment by ranesagar** [comment]
@abhinaybyrisetty - PTAL

**Comment by Badbond** [comment]
Thanks for rebasing @ranesagar. @abhinaybyrisetty did you have time to check this one out? Anything I can help with?

**Comment by abhinaybyrisetty** [comment]
LGTM, please bump the chart version to automatically publish the chart to helm repo.

**Comment by ranesagar** [comment]
@abhinaybyrisetty - PTAL

**Review by abhinaybyrisetty — APPROVED** [review]
LGTM

**Pull request merged**
